networks:
  vispyr:

services:
  init:
    image: &tempoImage grafana/tempo
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - ./tempo/data:/var/tempo

  tempo:
    image: *tempoImage
    command: ["-config.file=/etc/tempo.yaml"]
    container_name: tempo
    networks:
      - vispyr
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - ./tempo/data:/var/tempo
    ports:
      - "3200:3200" # tempo
    depends_on:
      - init

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - vispyr
    volumes:
      - ./prometheus/prom-config.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver

  pyroscope:
    image: grafana/pyroscope
    container_name: pyroscope
    volumes:
      - ./pyroscope/pyro-config.yaml:/etc/pyro-config.yaml
    command:
      - -config.file=/etc/pyro-config.yaml
    networks:
      - vispyr
    ports:
      - 4040:4040

  agent-collector:
    image: grafana/alloy
    container_name: agent-collector
    networks:
      - vispyr
    volumes:
      - ./alloy/agent-config.alloy:/etc/alloy/config.alloy
    ports:
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 9999:9999 # Pyroscope listen server
      - 12346:12346 # Debug UI
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12346
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - gateway-collector

 
  # agent-collector:
  #   image: otel/opentelemetry-collector-contrib
  #   container_name: agent-collector
  #   networks:
  #     - vispyr
  #   volumes:
  #     - ./otelcol/otelcol.yaml:/etc/otelcol-contrib/config.yaml
  #   ports:
  #     - 13133:13133 # health_check extension
  #     - 4317:4317 # OTLP gRPC receiver
  #     - 4318:4318 # OTLP http receiver
  #     - 55679:55679 # zpages extension
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   depends_on:
  #   - tempo
  #   - pyroscope
  #   - prometheus

  gateway-collector:
    image: grafana/alloy
    container_name: gateway-collector
    networks:
      - vispyr
    volumes:
      - ./alloy/gateway-config.alloy:/etc/alloy/config.alloy
    ports:
      - 12345:12345
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
    depends_on:
    - tempo
    - pyroscope
    - prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - vispyr
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - 3000:3000
    depends_on:
      - prometheus
      - tempo
      - pyroscope
