networks:
  vispyr:

services:
  init-tempo:
    image: &tempoImage grafana/tempo
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - ./tempo/data:/var/tempo

  init-prometheus:
    image: &promImage prom/prometheus
    user: root
    entrypoint:
      - "chown"
      - "65534:65534"
      - "/prometheus"
    volumes:
      - ./prometheus/data:/prometheus

  tempo:
    image: *tempoImage
    command: ["-config.file=/etc/tempo.yaml"]
    container_name: tempo
    networks:
      - vispyr
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - ./tempo/data:/var/tempo
    ports:
      - "3200:3200"
    depends_on:
      - init-tempo

  prometheus:
    image: *promImage
    container_name: prometheus
    networks:
      - vispyr
    volumes:
      - ./prometheus/prom-config.yaml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
      - --storage.tsdb.retention.time=30d
    depends_on:
      - init-prometheus

  pyroscope:
    image: grafana/pyroscope
    container_name: pyroscope
    volumes:
      - ./pyroscope/pyro-config.yaml:/etc/pyro-config.yaml
      - ./pyroscope/data:/data
    command:
      - --config.file=/etc/pyro-config.yaml
    networks:
      - vispyr
    ports:
      - 4040:4040

  gateway-collector:
    image: grafana/alloy
    container_name: gateway-collector
    networks:
      - vispyr
    volumes:
      - ./alloy/gateway-config.alloy:/etc/alloy/config.alloy
    ports:
      - 4317:4317 # OTLP gRPC receiver
      - 9090:9090 # Node metrics scraper http receiver
      - 9999:9999 # Pyroscope http receiver
    command:
      - run
      - /etc/alloy/config.alloy
    depends_on:
    - tempo
    - pyroscope
    - prometheus

  grafana:
    image: grafana/grafana
    user: "1000:1000"
    container_name: grafana
    networks:
      - vispyr
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - 3000:3000
    depends_on:
      - prometheus
      - tempo
      - pyroscope
