{
 "title": "Dynamic Service Labels for Latency",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "DS_PYROSCOPE", "query": "grafana-pyroscope-datasource" }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(http_client_request_duration_seconds_bucket[5m]))",
     "legendFormat": "P99 - {{exported_job}}"
    },
    {
     "expr": "histogram_quantile(0.95, rate(http_client_request_duration_seconds_bucket[5m]))",
     "legendFormat": "P95 - {{exported_job}}"
    },
    {
     "expr": "histogram_quantile(0.90, rate(http_client_request_duration_seconds_bucket[5m]))",
     "legendFormat": "P90 - {{exported_job}}"
    },
    {
     "expr": "histogram_quantile(0.50, rate(http_client_request_duration_seconds_bucket[5m]))",
     "legendFormat": "P50 - {{exported_job}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "Average CPU Utilization Across All Logical Cores"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)",
     "legendFormat": "System Memory Not Immediately Available Without Impact On Performance"
    }
   ]
  },
  {
   "title": "Profile",
   "type": "flamegraph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "labelSelector": "{}",
     "profileTypeId": "wall:samples:count:wall:nanoseconds"
    }
   ]
  }
 ]
}